name: peer7
services:
  yacy-cf-backend-7:
    container_name: yacy-cf-backend-7
    depends_on:
    - yacy-server-7
    environment:
    - FLASK_ENV=development
    - YACY_USERNAME=admin
    - YACY_PASSWORD=yacy
    - YACY_PORT=8099
    - YACY_SERVICE=yacy-server-7
    - SERVER_FLASK_HOST=0.0.0.0
    - SERVER_FLASK_PORT=3009
    - SOCKET_HOST=0.0.0.0
    - SOCKET_PORT=8199
    - DEBUG_ONLY_LISTEN=0
    - DEBUG_AUTO_WHITELIST=1
    - DEBUG_AUTO_WHITELIST_NUM_NODES=10
    expose:
    - '3009'
    - '8199'
    hostname: yacy-cf-backend-7
    image: dul800/yacy_cf_backend:1.0
    ports:
    - 3009:3009
    - 8199:8199
    restart: always
    volumes:
    - ./evaluation_results:/yacy_cf_backend/resources/data
    - ./histories:/yacy_cf_backend/resources/history
    - ./whitelist:/yacy_cf_backend/resources/whitelist
  yacy-cf-frontend-7:
    container_name: yacy-cf-frontend-7
    depends_on:
    - yacy-cf-backend-7
    environment:
    - REACT_APP_API_PORT=3009
    - REACT_APP_BACKEND_ADDRESS=localhost
    - PORT=4009
    expose:
    - '4009'
    image: dul800/yacy_cf_frontend:latest
    ports:
    - 4009:4009
    restart: always
  yacy-server-7:
    container_name: yacy-server-7
    expose:
    - '8099'
    hostname: yacy-server-7
    image: yacy/yacy_search_server:latest
    ports:
    - 8099:8099
    - 8451:8451
version: '0.2'
volumes:
  evaluation_results: null
