name: peer0
services:
  yacy-cf-backend-0:
    container_name: yacy-cf-backend-0
    depends_on:
    - yacy-server-0
    environment:
    - FLASK_ENV=development
    - YACY_USERNAME=admin
    - YACY_PASSWORD=yacy
    - YACY_PORT=8092
    - YACY_SERVICE=yacy-server-0
    - SERVER_FLASK_HOST=0.0.0.0
    - SERVER_FLASK_PORT=3002
    - SOCKET_HOST=0.0.0.0
    - SOCKET_PORT=8192
    - DEBUG_ONLY_LISTEN=0
    - DEBUG_AUTO_WHITELIST=1
    - DEBUG_AUTO_WHITELIST_NUM_NODES=10
    expose:
    - '3002'
    - '8192'
    hostname: yacy-cf-backend-0
    image: dul800/yacy_cf_backend:1.0
    ports:
    - 3002:3002
    - 8192:8192
    restart: always
    volumes:
    - ./evaluation_results:/yacy_cf_backend/resources/data
    - ./histories:/yacy_cf_backend/resources/history
    - ./whitelist:/yacy_cf_backend/resources/whitelist
  yacy-cf-frontend-0:
    container_name: yacy-cf-frontend-0
    depends_on:
    - yacy-cf-backend-0
    environment:
    - REACT_APP_API_PORT=3002
    - REACT_APP_BACKEND_ADDRESS=localhost
    - PORT=4002
    expose:
    - '4002'
    image: dul800/yacy_cf_frontend:latest
    ports:
    - 4002:4002
    restart: always
  yacy-server-0:
    container_name: yacy-server-0
    expose:
    - '8092'
    hostname: yacy-server-0
    image: yacy/yacy_search_server:latest
    ports:
    - 8092:8092
    - 8444:8444
version: '0.2'
volumes:
  evaluation_results: null
