name: peer2
services:
  yacy-cf-backend-2:
    container_name: yacy-cf-backend-2
    depends_on:
    - yacy-server-2
    environment:
    - FLASK_ENV=development
    - YACY_USERNAME=admin
    - YACY_PASSWORD=yacy
    - YACY_PORT=8094
    - YACY_SERVICE=yacy-server-2
    - SERVER_FLASK_HOST=0.0.0.0
    - SERVER_FLASK_PORT=3004
    - SOCKET_HOST=0.0.0.0
    - SOCKET_PORT=8194
    - DEBUG_ONLY_LISTEN=0
    - DEBUG_AUTO_WHITELIST=1
    - DEBUG_AUTO_WHITELIST_NUM_NODES=10
    expose:
    - '3004'
    - '8194'
    hostname: yacy-cf-backend-2
    image: dul800/yacy_cf_backend:1.0
    ports:
    - 3004:3004
    - 8194:8194
    restart: always
    volumes:
    - ./evaluation_results:/yacy_cf_backend/resources/data
    - ./histories:/yacy_cf_backend/resources/history
    - ./whitelist:/yacy_cf_backend/resources/whitelist
  yacy-cf-frontend-2:
    container_name: yacy-cf-frontend-2
    depends_on:
    - yacy-cf-backend-2
    environment:
    - REACT_APP_API_PORT=3004
    - REACT_APP_BACKEND_ADDRESS=localhost
    - PORT=4004
    expose:
    - '4004'
    image: dul800/yacy_cf_frontend:latest
    ports:
    - 4004:4004
    restart: always
  yacy-server-2:
    container_name: yacy-server-2
    expose:
    - '8094'
    hostname: yacy-server-2
    image: yacy/yacy_search_server:latest
    ports:
    - 8094:8094
    - 8446:8446
version: '0.2'
volumes:
  evaluation_results: null
